### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'outputs'

### ISSUE THREAD

**Issue by Redifinejyb** [cwq159/PyTorch-Spiking-YOLOv3#4]
D:\ANACONDA\envs\Mytorch\python.exe D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py
Namespace(augment=False, batch_size=2, cache_images=False, cfg='cfg/yolov3-spp.cfg', channel_wise=False, conf_thres=0.001, data='data/coco2017.data', device='', img_size=[320, 640, 640], iou_thres=0.6, multi_scale=False, rect=False, reset_mode='subtraction', save_file='yolov3-tiny-ours-snn', save_json=True, single_cls=False, statistics_iters=30, task='test', timesteps=16, weights='weights/yolov3-spp-ultralytics.pt')
Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1060 3GB', total_memory=3072MB)

Caching labels data\coco\trainvalno5k.txt (68 found, 0 missing, 1 empty, 0 duplicate, for 69 images): 100%|██████████| 69/69 [00:00<00:00, 4068.65it/s]
Model Summary: 222 layers, 6.19491e+07 parameters, 6.19491e+07 gradients
add node conv1: ['dag_input0']->['conv1_out1']
add node conv2: ['conv1_out1']->['conv2_out1']
add node conv3: ['conv2_out1']->['conv3_out1']
add node conv4: ['conv3_out1']->['conv4_out1']
Traceback (most recent call last):
  File "D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py", line 184, in <module>
    transformer.inference_get_status(dataloader, opt.statistics_iters)
  File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\snn_transformer.py", line 94, in inference_get_status
    self.init_dag([data])
  File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\snn_transformer.py", line 69, in init_dag
    self.snn_dag = ann_parser.parse_ann_model(self.original_net, inputs)
  File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\ann_parser.py", line 221, in parse_ann_model
    model(*warpped_input)
  File "D:\ANACONDA\envs\Mytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py", line 52, in forward
    x = self.list[i](x)
  File "D:\ANACONDA\envs\Mytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'outputs'

Process finished with exit code 1

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Yolov3-spp hasn’t been supported yet.
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Weiqian Chen
                            
                            
                                
                            
                    
                        
                            
                                    cwq@pku.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 12/21/2020 14:45，Redifinejyb<notifications@github.com> wrote： 




D:\ANACONDA\envs\Mytorch\python.exe D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py

Namespace(augment=False, batch_size=2, cache_images=False, cfg='cfg/yolov3-spp.cfg', channel_wise=False, conf_thres=0.001, data='data/coco2017.data', device='', img_size=[320, 640, 640], iou_thres=0.6, multi_scale=False, rect=False, reset_mode='subtraction', save_file='yolov3-tiny-ours-snn', save_json=True, single_cls=False, statistics_iters=30, task='test', timesteps=16, weights='weights/yolov3-spp-ultralytics.pt')

Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1060 3GB', total_memory=3072MB)

Caching labels data\coco\trainvalno5k.txt (68 found, 0 missing, 1 empty, 0 duplicate, for 69 images): 100%|██████████| 69/69 [00:00<00:00, 4068.65it/s]

Model Summary: 222 layers, 6.19491e+07 parameters, 6.19491e+07 gradients

add node conv1: ['dag_input0']->['conv1_out1']

add node conv2: ['conv1_out1']->['conv2_out1']

add node conv3: ['conv2_out1']->['conv3_out1']

add node conv4: ['conv3_out1']->['conv4_out1']

Traceback (most recent call last):

File "D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py", line 184, in 

transformer.inference_get_status(dataloader, opt.statistics_iters)

File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\snn_transformer.py", line 94, in inference_get_status

self.init_dag([data])

File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\snn_transformer.py", line 69, in init_dag

self.snn_dag = ann_parser.parse_ann_model(self.original_net, inputs)

File "D:\SNN\PyTorch-Spiking-YOLOv3-ultralytics\spiking_utils\ann_parser.py", line 221, in parse_ann_model

model(*warpped_input)

File "D:\ANACONDA\envs\Mytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl

result = self.forward(*input, **kwargs)

File "D:/SNN/PyTorch-Spiking-YOLOv3-ultralytics/ann_to_snn.py", line 52, in forward

x = self.listi

File "D:\ANACONDA\envs\Mytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl

result = self.forward(*input, **kwargs)

TypeError: forward() missing 1 required positional argument: 'outputs'

Process finished with exit code 1



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
