### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Kyle-fang** [cwq159/PyTorch-Spiking-YOLOv3#44]

**Comment by Kyle-fang** [comment]
Traceback (most recent call last):
  File "ann_to_snn.py", line 184, in <module>
    snn_results, maps, firing_ratios = snn_evaluate(opt,
  File "/kyle/Pytorch-Spiking-YOLOv3/spiking_utils/snn_evaluate.py", line 276, in snn_evaluate
    output_snn1, output_snn2 = snn(data)  # two branches
ValueError: too many values to unpack (expected 2)

**Comment by Kyle-fang** [comment]
python=3.8
pytorch=1.11

**Comment by Kyle-fang** [comment]
I downgraded the environment version solved the problem， used  python=3.7. pytorch=1.3
