### ISSUE TITLE
got a cudnn error when running ann_to_snn.py

### ISSUE THREAD

**Issue by xuhelene** [cwq159/PyTorch-Spiking-YOLOv3#53]
_Traceback (most recent call last):
  File "ann_to_snn.py", line 182, in <module>
    opt.augment)
  File "/root/code/PyTorch-Spiking-YOLOv3-ultralytics/spiking_utils/snn_evaluate.py", line 276, in snn_evaluate
    output_snn1, output_snn2 = snn(data)  # two branches
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/code/PyTorch-Spiking-YOLOv3-ultralytics/spiking_utils/spike_dag.py", line 102, in forward
    print(" op['op'](*op_inputs) = ",  op['op'](*op_inputs))
  File "/root/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/code/PyTorch-Spiking-YOLOv3-ultralytics/spiking_utils/spike_layer.py", line 75, in forward
    self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input._

my environment:
python==3.7.6
pytorch==1.3.0
cuda==10.1

**Comment by xuhelene** [comment]
I searched the internet and found that someone said it might be  the memory issue, I changed the timesteps and solved the problem
