### ISSUE TITLE
寻求大佬帮助，这个问题怎么解决

### ISSUE THREAD

**Issue by 123456ZF** [cwq159/PyTorch-Spiking-YOLOv3#56]
Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Model Summary: 225 layers, 6.29987e+07 parameters, 6.29987e+07 gradients
Optimizer groups: 76 .bias, 76 Conv2d.weight, 73 other
Traceback (most recent call last):
  File "/home/chenqq/anaconda3/envs/smoke/Spiking_YOLOv3/train.py", line 435, in <module>
    train(hyp)  # train normally
  File "/home/chenqq/anaconda3/envs/smoke/Spiking_YOLOv3/train.py", line 199, in train
    single_cls=opt.single_cls)
  File "/home/chenqq/anaconda3/envs/smoke/Spiking_YOLOv3/utils/datasets.py", line 278, in __init__
    assert n > 0, 'No images found in %s. See %s' % (path, help_url)
AssertionError: No images found in /home/chenqq/anaconda3/envs/smoke/Spiking_YOLOv3/data/coco2017/train.txt. See https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

**Comment by Bender-long** [comment]
路径问题或者是数据集没处理好。

**Comment by Bender-long** [comment]
数据集处理可以看这个视频https://www.bilibili.com/video/BV1t54y1C7ra

**Comment by Bender-long** [comment]
数据集处理可以看这个视频https://www.bilibili.com/video/BV1t54y1C7ra

**Comment by 123456ZF** [comment]
@Bender-long 请问您跑通了ann-snn吗，我用的gtx3060，环境torch 1.7.1+cu101 python3.7 出现了问题：ValueError:too many values to unpack(expected 2) 报错的位置是snn_evaluate.py,line 97 ( output_snn1,output_snn2=snn(data) 这个位置)，请问有什么解决办法吗？

**Comment by 123456ZF** [comment]
@Bender-long非常感谢您的回答

**Comment by Bender-long** [comment]
你好，请加我QQ联系：2033384707




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] 寻求大佬帮助，这个问题怎么解决 (Issue #56)





 
@Bender-long 请问您跑通了ann-snn吗，我用的gtx3060，环境torch 1.7.1+cu101 python3.7 出现了问题：ValueError:too many values to unpack(expected 2) 报错的位置是snn_evaluate.py,line 97 ( output_snn1,output_snn2=snn(data) 这个位置)，请问有什么解决办法吗？

**Comment by Bender-L** [comment]
> 你好，请加我QQ联系：2033384707
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cwq159/PyTorch-Spiking-YOLOv3" ***@***.***&gt;; 发送时间:&nbsp;2023年3月14日(星期二) 下午3:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] 寻求大佬帮助，这个问题怎么解决 (Issue #56) @Bender-long 请问您跑通了ann-snn吗，我用的gtx3060，环境torch 1.7.1+cu101 python3.7 出现了问题：ValueError:too many values to unpack(expected 2) 报错的位置是snn_evaluate.py,line 97 ( output_snn1,output_snn2=snn(data) 这个位置)，请问有什么解决办法吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我只是个大四的本科生，啥都不会

**Comment by sun133233** [comment]
> @Bender-long 请问您跑通了ann-snn吗，我用的gtx3060，环境torch 1.7.1+cu101 python3.7 出现了问题：ValueError:too many values to unpack(expected 2) 报错的位置是snn_evaluate.py,line 97 ( output_snn1,output_snn2=snn(data) 这个位置)，请问有什么解决办法吗？


遇到了同样的问题，请问解决了吗

**Comment by Bender-long** [comment]
您好，该问题是torch版本太高导致的，我当时使用torch1.4就没有报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cwq159/PyTorch-Spiking-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cwq159/PyTorch-Spiking-YOLOv3] 寻求大佬帮助，这个问题怎么解决 (Issue #56)





  
@Bender-long 请问您跑通了ann-snn吗，我用的gtx3060，环境torch 1.7.1+cu101 python3.7 出现了问题：ValueError:too many values to unpack(expected 2) 报错的位置是snn_evaluate.py,line 97 ( output_snn1,output_snn2=snn(data) 这个位置)，请问有什么解决办法吗？
  
遇到了同样的问题，请问解决了吗

**Comment by 123456ZF** [comment]
@sun133233 gtx3060你这太高了,你可以考虑降低显卡版本,然后下载torch1.6可以的,我是1660ti的

**Comment by sun133233** [comment]
@Bender-long 解决了真的太感谢了！

**Comment by sun133233** [comment]
> @sun133233 gtx3060你这太高了,你可以考虑降低显卡版本,然后下载torch1.6可以的,我是1660ti的

@123456ZF 解决了真的太感谢了！
