### ISSUE TITLE
Failed to train the network when the  input is grayscale image

### ISSUE THREAD

**Issue by tomorrow-mouse** [cwq159/PyTorch-Spiking-YOLOv3#6]
Thanks for your great work!!! The work helps me a lot though I have met some problems:
It  seems that  the train process doesn't work when the input are grayscale images. I have tried the yolov3-tiny.cfg and yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg int the cfg directory, and the result shows that neither of them work.
However, when I try the latest [ultralytics/yolov3](https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data), the train process works well. 
Can you tell me which version of ultralytics/yolov3 is your base work?  And any other advice?

Thanks and Best Regards

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Have you tried other datasets? Please show your training process in detail.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Weiqian Chen
                            
                            
                                
                            
                    
                        
                            
                                    cwq@pku.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/10/2021 16:42，tomorrow-mouse<notifications@github.com> wrote： 



Thanks for your great work!!! The work helps me a lot though I have met some problems:
It  seems that  the train process doesn't work when the input are grayscale images. I have tried the yolov3-tiny.cfg and yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg int the cfg directory, and the result shows that neither of them work.
However, when I try the latest ultralytics/yolov3, the train process works well.
Can you tell me which version of ultralytics/yolov3 is your base work?  And any other advice?
Thanks and Best Regards

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tomorrow-mouse** [comment]
Thans for your reply!
I have tried coco and voc dataset， both of them will work. 
And when the input are my own grayscale images, the train process is shown below( I have tried "yolov3-tiny-1cls.cfg"、"yolov3-tiny.cfg" and your yolov3 cfg, the results are same. ):
`root@f13ce7114bc1:/usr/src/app# python3 train.py --img 640 --batch 16 --cfg cfg/yolov3-tiny-1cls.cfg  --data data/dvs.data --device 1 --weights '' --epochs 500
Namespace(adam=False, batch_size=16, bucket='', cache_images=False, cfg='cfg/yolov3-tiny-1cls.cfg', data='data/dvs.data', device='1', epochs=500, evolve=False, freeze_layers=False, img_size=[640, 640, 640], multi_scale=False, name='', nosave=False, notest=False, rect=False, resume=False, single_cls=False, weights='')
Using CUDA Apex device0 _CudaDeviceProperties(name='Tesla V100-PCIE-32GB', total_memory=32510MB)

Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
WARNING: smart bias initialization failure.
WARNING: smart bias initialization failure.
Model Summary: 37 layers, 8.66988e+06 parameters, 8.66988e+06 gradients
Optimizer groups: 13 .bias, 13 Conv2d.weight, 11 other
Caching labels VOCdevkit/VOC2007/labels.npy (284 found, 0 missing, 0 empty, 0 duplicate, fo
Caching labels VOCdevkit/VOC2007/labels.npy (284 found, 0 missing, 0 empty, 0 duplicate, fo
Image sizes 640 - 640 train, 640 test
Using 8 dataloader workers
Starting training for 500 epochs...

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|                                                               | 0/18 [00:00<?, ?it/s]/opt/conda/lib/python3.8/site-packages/torch/cuda/memory.py:344: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  warnings.warn(
     0/499     2.73G       6.5       101         0       107        27       640:  17%|▏|      0/499     2.73G      6.48      91.7         0      98.2        31       640:  17%|▏|      0/499     2.73G      6.48      91.7         0      98.2        31       640:  22%|▏|      0/499     2.73G      6.44      80.7         0      87.2        42       640:  22%|▏|      0/499     2.73G      6.44      80.7         0      87.2        42       640:  28%|▎|      0/499     2.73G      6.36      70.6         0      76.9        24       640:  28%|▎|      0/499     2.73G      6.26      62.1         0      68.3        29       640:  28%|▎|      0/499     2.73G      6.26      62.1         0      68.3        29       640:  39%|▍|      0/499     2.73G      6.15      55.1         0      61.2        29       640:  39%|▍|      0/499     2.73G      6.04      49.4         0      55.4        23       640:  39%|▍|      0/499     2.73G      6.04      49.4         0      55.4        23       640:  50%|▌|      0/499     2.73G      5.95      44.7         0      50.7        37       640:  50%|▌|      0/499     2.73G      5.83      40.9         0      46.7        50       640:  50%|▌|      0/499     2.73G      5.83      40.9         0      46.7        50       640:  61%|▌|      0/499     2.73G      5.69      37.6         0      43.3        28       640:  61%|▌|      0/499     2.73G       5.6      34.8         0      40.4        28       640:  61%|▌|      0/499     2.73G       5.6      34.8         0      40.4        28       640:  72%|▋|      0/499     2.73G      5.55      32.4         0        38        36       640:  72%|▋|      0/499     2.73G      5.44      30.3         0      35.8        32       640:  72%|▋|      0/499     2.73G      5.44      30.3         0      35.8        32       640:  83%|▊|      0/499     2.73G      5.35      28.5         0      33.9        32       640:  83%|▊|      0/499     2.73G      5.25      26.9         0      32.2        38       640:  83%|▊|      0/499     2.73G      5.25      26.9         0      32.2        38       640:  94%|▉|      0/499     6.06G       5.2      25.5         0      30.7        27       640:  94%|▉|      0/499     6.06G       5.2      25.5         0      30.7        27       640: 100%|█| 1
               Class    Images   Targets         P         R   mAP@0.5        F1:  17%|▏|                Class    Images   Targets         P         R   mAP@0.5        F1:  28%|▎|                Class    Images   Targets         P         R   mAP@0.5        F1:  44%|▍|                Class    Images   Targets         P         R   mAP@0.5        F1:  67%|▋|                Class    Images   Targets         P         R   mAP@0.5        F1:  89%|▉|                Class    Images   Targets         P         R   mAP@0.5        F1: 100%|█| 1
                 all       284       524         0         0         0         0

     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
     1/499     2.28G      3.92      1.12         0      5.04        27       640:  17%|▏|      1/499     2.28G      3.97      1.12         0      5.09        29       640:  17%|▏|      1/499     2.28G      3.97      1.12         0      5.09        29       640:  22%|▏|      1/499     2.28G         4       1.2         0      5.19        39       640:  22%|▏|      1/499     2.28G      3.96      1.25         0      5.21        33       640:  22%|▏|      1/499     2.28G      3.96      1.25         0      5.21        33       640:  33%|▎|      1/499     2.28G      3.96      1.28         0      5.24        37       640:  33%|▎|      1/499     2.28G      3.94      1.27         0       5.2        32       640:  33%|▎|      1/499     2.28G      3.94      1.27         0       5.2        32       640:  44%|▍|      1/499     2.28G      3.85      1.24         0      5.09        28       640:  44%|▍|      1/499     2.28G      3.96      1.19         0      5.15        23       640:  44%|▍|      1/499     2.28G      3.96      1.19         0      5.15        23       640:  56%|▌|      1/499     2.28G      3.95      1.19         0      5.14        35       640:  56%|▌|      1/499     2.28G      3.97      1.17         0      5.13        31       640:  56%|▌|      1/499     2.28G      3.97      1.17         0      5.13        31       640:  67%|▋|      1/499     2.28G      3.96      1.17         0      5.13        33       640:  67%|▋|      1/499     2.28G      3.95      1.18         0      5.13        34       640:  67%|▋|      1/499     2.28G      3.95      1.18         0      5.13        34       640:  78%|▊|      1/499     2.28G      3.92      1.18         0       5.1        28       640:  78%|▊|      1/499     2.28G      3.87      1.19         0      5.05        34       640:  78%|▊|      1/499     2.28G      3.87      1.19         0      5.05        34       640:  89%|▉|      1/499     2.28G      3.82      1.18         0      5.01        32       640:  89%|▉|      1/499     2.28G      3.81       1.2         0      5.01        28       640:  89%|▉|      1/499     2.28G      3.81       1.2         0      5.01        28       640: 100%|█|      1/499     2.28G      3.81       1.2         0      5.01        28       640: 100%|█| 1
               Class    Images   Targets         P         R   mAP@0.5        F1:  22%|▏|                Class    Images   Targets         P         R   mAP@0.5        F1:  33%|▎|                Class    Images   Targets         P         R   mAP@0.5        F1:  44%|▍|                Class    Images   Targets         P         R   mAP@0.5        F1:  56%|▌|                Class    Images   Targets         P         R   mAP@0.5        F1:  67%|▋|                Class    Images   Targets         P         R   mAP@0.5        F1:  83%|▊|                Class    Images   Targets         P         R   mAP@0.5        F1: 100%|█| 1
                 all       284       524         0         0         0         0`

when the epochs become 50 、100 even 200, the process will never change, like this:
` Class    Images   Targets         P         R   mAP@0.5        F1:  22%|▏|                Class    Images   Targets         P         R   mAP@0.5        F1:  33%|▎|                Class    Images   Targets         P         R   mAP@0.5        F1:  44%|▍|                Class    Images   Targets         P         R   mAP@0.5        F1:  56%|▌|                Class    Images   Targets         P         R   mAP@0.5        F1:  67%|▋|                Class    Images   Targets         P         R   mAP@0.5        F1:  78%|▊|                Class    Images   Targets         P         R   mAP@0.5        F1:  89%|▉|                Class    Images   Targets         P         R   mAP@0.5        F1: 100%|█|                Class    Images   Targets         P         R   mAP@0.5        F1: 100%|█| 1
                 all       284       524         0         0    0.0167         0
`

It seems that the precision、 recall 、f1 will keep 0 in the train process,  and the mAP maintains a small value.

Is it possible that the work, you are referring to,  does not support grayscale images at that time ? As I mentioned, the train process doesn't work for grayscale images even the cfg file is origin "yolov3-tiny.cfg"

**Comment by tomorrow-mouse** [comment]
Dear cwq159，
       Here is the firgure on tensorboard. Hope for your reply!
       ![Screenshot from 2021-01-11 14-40-15](https://user-images.githubusercontent.com/31956693/104152623-0a625a00-541b-11eb-8071-947645766533.png)

**Comment by cwq159** [comment]
For training problems, you can refer to ultralytics/yolov3. Maybe you should revise datasets.py in /utils or the code for data preprocessing(such as [0,255] to [0,1]).

**Comment by tomorrow-mouse** [comment]
Thanks, worthy to try ! Besides, could you tell me the version or the time of ultralytics/yolov3 that your work is based on ?

**Comment by cwq159** [comment]
almost two months ago

**Comment by tomorrow-mouse** [comment]
Hello, cwq159:
       I have successfully trained the neural network based on my  grayscale images. Thanks for your advice.
       And when I transform the trained network to snn, the error occurs:
       
![image](https://user-images.githubusercontent.com/31956693/104563823-210be980-5685-11eb-8f0f-a1b603399ef7.png)
      Hoping for some ideas.

**Comment by tomorrow-mouse** [comment]
I have found something weird.  I firstly trained the network on part of voc dataset which include aboult 100 3-channel images. However, when I transform the trained network to snn, same error occurs:

 root@8f80e22fa1e6:/usr/src/app# python ann_to_snn.py --cfg cfg/voc-yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg --data data/2007.data --weights weights/last.pt --timesteps 128 --device 4
Namespace(augment=False, batch_size=16, cache_images=False, cfg='cfg/voc-yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg', channel_wise=False, conf_thres=0.001, data='data/2007.data', device='4', img_size=[320, 640, 640], iou_thres=0.6, multi_scale=False, rect=False, reset_mode='subtraction', save_file='yolov3-tiny-ours-snn', save_json=False, single_cls=False, statistics_iters=30, task='test', timesteps=128, weights='weights/last.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-PCIE-32GB', total_memory=32510MB)

Caching labels MOCdevkit/VOC2007/labels.npy (86 found, 0 missing, 0 empty, 0 duplicate, for 86 images): 100%|█████████████████████████████████████]████| 86/86 [00:00<00:00, 6941.27it/s]
WARNING: smart bias initialization failure.
WARNING: smart bias initialization failure.
Model Summary: 55 layers, 9.64813e+06 parameters, 9.64813e+06 gradients
inp size 0
torch.Size([16, 3, 640, 640])
1
add node conv1: ['dag_input0']->['conv1_out1']
torch.Size([16, 16, 640, 640])
Traceback (most recent call last):
  File "ann_to_snn.py", line 178, in <module>
    transformer.inference_get_status(dataloader, opt.statistics_iters)
  File "/usr/src/app/spiking_utils/snn_transformer.py", line 94, in inference_get_status
    self.init_dag([data])
  File "/usr/src/app/spiking_utils/snn_transformer.py", line 69, in init_dag
    self.snn_dag = ann_parser.parse_ann_model(self.original_net, inputs)
  File "/usr/src/app/spiking_utils/ann_parser.py", line 225, in parse_ann_model
    model(*warpped_input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "ann_to_snn.py", line 53, in forward
    x = self.list[i](x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/usr/src/app/spiking_utils/ann_parser.py", line 56, in relu_wrapper
    in_nodes = [find_node_by_tensor(inp)]
  File "/usr/src/app/spiking_utils/ann_parser.py", line 10, in find_node_by_tensor
    raise ValueError("cannot find tensor Size", tensor.size())
ValueError: ('cannot find tensor Size', torch.Size([16, 16, 640, 640]))


I have no idea about the phenomenon. Have any advice?

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Please use PyTorch1.3
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Weiqian Chen
                            
                            
                                
                            
                    
                        
                            
                                    cwq@pku.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/14/2021 22:53，tomorrow-mouse<notifications@github.com> wrote： 




I have found something weird.  I firstly trained the network on part of voc dataset which include aboult 100 3-channel images. However, when I transform the trained network to snn, same error occurs:

root@8f80e22fa1e6:/usr/src/app# python ann_to_snn.py --cfg cfg/voc-yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg --data data/2007.data --weights weights/last.pt --timesteps 128 --device 4

Namespace(augment=False, batch_size=16, cache_images=False, cfg='cfg/voc-yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg', channel_wise=False, conf_thres=0.001, data='data/2007.data', device='4', img_size=[320, 640, 640], iou_thres=0.6, multi_scale=False, rect=False, reset_mode='subtraction', save_file='yolov3-tiny-ours-snn', save_json=False, single_cls=False, statistics_iters=30, task='test', timesteps=128, weights='weights/last.pt')

Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-PCIE-32GB', total_memory=32510MB)

Caching labels MOCdevkit/VOC2007/labels.npy (86 found, 0 missing, 0 empty, 0 duplicate, for 86 images): 100%|█████████████████████████████████████]████| 86/86 [00:00<00:00, 6941.27it/s]

WARNING: smart bias initialization failure.

WARNING: smart bias initialization failure.

Model Summary: 55 layers, 9.64813e+06 parameters, 9.64813e+06 gradients

inp size 0

torch.Size([16, 3, 640, 640])

1

add node conv1: ['dag_input0']->['conv1_out1']

torch.Size([16, 16, 640, 640])

Traceback (most recent call last):

File "ann_to_snn.py", line 178, in 

transformer.inference_get_status(dataloader, opt.statistics_iters)

File "/usr/src/app/spiking_utils/snn_transformer.py", line 94, in inference_get_status

self.init_dag([data])

File "/usr/src/app/spiking_utils/snn_transformer.py", line 69, in init_dag

self.snn_dag = ann_parser.parse_ann_model(self.original_net, inputs)

File "/usr/src/app/spiking_utils/ann_parser.py", line 225, in parse_ann_model

model(*warpped_input)

File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl

result = self.forward(*input, **kwargs)

File "ann_to_snn.py", line 53, in forward

x = self.listi

File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl

result = self.forward(*input, **kwargs)

File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward

input = module(input)

File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 744, in _call_impl

result = self.forward(*input, **kwargs)

File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 102, in forward

return F.relu(input, inplace=self.inplace)

File "/usr/src/app/spiking_utils/ann_parser.py", line 56, in relu_wrapper

in_nodes = [find_node_by_tensor(inp)]

File "/usr/src/app/spiking_utils/ann_parser.py", line 10, in find_node_by_tensor

raise ValueError("cannot find tensor Size", tensor.size())

ValueError: ('cannot find tensor Size', torch.Size([16, 16, 640, 640]))

I have no idea about the phenomenon. Have any advice?



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by cwq159** [comment]
Please use PyTorch1.3
