### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by HaoyuYao** [cwq159/PyTorch-Spiking-YOLOv3#61]
Traceback (most recent call last):
  File "ann_to_snn.py", line 205, in <module>
    dataloader=dataloader)
  File "/home/PyTorch-Spiking-YOLOv3/spiking_utils/snn_evaluate.py", line 278, in snn_evaluate
    output_snn1, output_snn2 = snn(data)  # two branches
ValueError: too many values to unpack (expected 2)

**Comment by Ariella1128** [comment]
I'm having the same error. Did you solve it?

**Comment by uefall** [comment]
torch版本高了，解析出来的output nodes不对，建议用低版本torch

**Comment by SongFan-zju** [comment]
> torch版本高了，解析出来的output nodes不对，建议用低版本torch

您好，为什么我1.2.0的版本还是无法解析出来

**Comment by SongFan-zju** [comment]
> I'm having the same error. Did you solve it?

请问你解决了这个问题吗
