### ISSUE TITLE
When using yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, some dimension error will occurs in test.pytest.py

### ISSUE THREAD

**Issue by hjp-muser** [cwq159/PyTorch-Spiking-YOLOv3#7]
After training with the yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, there are some errors in test.py.

python3 test.py --cfg cfg/test.cfg --data data/dvs.data --weights weights/last.pt --device 4 
Namespace(augment=False, batch_size=16, cfg='cfg/test.cfg', conf_thres=0.001, data='data/dvs.data', device='4', img_size=512, iou_thres=0.6, save_json=False, single_cls=False, task='test', weights='weights/last.pt')
test
cfg/test.cfg data/dvs.data 16 512 0.001 0.6
Using CUDA device0 _CudaDeviceProperties(name='Tesla V100-PCIE-32GB', total_memory=32510MB)

Model Summary: 55 layers, 9.60424e+06 parameters, 9.60424e+06 gradients
Fusing layers...
Model Summary: 38 layers, 9.60044e+06 parameters, 9.60044e+06 gradients
Caching labels VOCdevkit/VOC2007/labels.npy (1 found, 0 missing, 0 empty, 0 duplicate, for 
Traceback (most recent call last):
  File "test.py", line 274, in <module>
    opt.augment)
  File "test.py", line 85, in test
    _ = model(torch.zeros((1, 3, imgsz, imgsz), device=device)) if device.type != 'cpu' else None  # run once
  File "/home/mengh3/.conda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/mengh3/PyTorch-cp/models.py", line 276, in forward
    return self.forward_once(x)
  File "/data/mengh3/PyTorch-cp/models.py", line 326, in forward_once
    x = module(x, out)  # WeightedFeatureFusion(), FeatureConcat()
  File "/home/mengh3/.conda/envs/yolov3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/mengh3/PyTorch-cp/utils/layers.py", line 35, in forward
    return torch.cat([outputs[i] for i in self.layers], 1) if self.multiple else outputs[self.layers[0]]
**RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 32 and 8 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71**

However, when using yolov3-tiny.cfg, everything goes well.

**Comment by ppx-hub** [comment]
when training with the yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, which weights should i choose？
if i continue using yolov3-tiny.weights, there are some error:
**RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 284204**
how to fix it , thank you

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Train from scratch
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                cwq
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/23/2021 ***@***.***> wrote： 




when training with the yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, which weights should i choose？

if i continue using yolov3-tiny.weights, there are some error:

RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 284204

how to fix it , thank you



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ppx-hub** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Train from scratch cwq ***@***.*** 签名由 网易邮箱大师 定制 On 03/23/2021 ***@***.***> wrote： when training with the yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, which weights should i choose？ if i continue using yolov3-tiny.weights, there are some error: RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 284204 how to fix it , thank you —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

thanks a lot. 
but when i want to train from scratch, i run train.py, and it seems that the --weight ''  will cause the following error:
**FileNotFoundError: [Errno 2] No such file or directory: "''"**
my command is python train.py --data data/rbc.data --cfg cfg/yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg --epochs 10 --weights ''    
i debug the train.py and find the weights variable is '\'\'', so i add this code to remove ''
![3](https://user-images.githubusercontent.com/57823330/112146081-1ab26480-8c16-11eb-9754-a4b4d2b47c7f.jpg)
this way, the len(weights) will equals to 0, and no longer execute "load_darknet_weights(model, weights)"

my question is that is this the correct way to train  from scratch? Looking forward to your reply

**Comment by cwq159** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        I think it’s not due to the weights file. You better check your error in detail.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                cwq
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/23/2021 ***@***.***> wrote： 






font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } Train from scratch cwq @.*** 签名由 网易邮箱大师 定制 On 03/23/2021 @.***> wrote： when training with the yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg, which weights should i choose？ if i continue using yolov3-tiny.weights, there are some error: RuntimeError: shape '[256, 384, 3, 3]' is invalid for input of size 284204 how to fix it , thank you —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



thanks a lot.

but when i want to train from scratch, i run train.py, and it seems that the --weight ''  will cause the following error:

FileNotFoundError: [Errno 2] No such file or directory: "''"

my command is python train.py --data data/rbc.data --cfg cfg/yolov3-tiny-mp2conv-mp1none-lk2relu-up2tconv.cfg --epochs 10 --weights ''

i debug the train.py and find the weights variable is '''', so i add this code to remove ''



this way, the len(weights) will equals to 0, and no longer execute "load_darknet_weights(model, weights)"

my question is that is this the correct way to train  from scratch? Looking forward to your reply



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
